version: '3'

services: 
  webserver:
    container_name: webserver
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/api
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    networks: 
      - app-networks

  api:
    container_name: api
    tty: true
    build:
      context: docker/php
      args: 
        user: dev
        uid: 1000
    working_dir: /var/www/api
    restart: unless-stopped
    volumes:
      - ./api:/var/www/api
    networks:
      - app-networks

  mysql:
    container_name: database
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment: 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - app-networks
networks: 
  app-networks:
    driver: bridge
  
    